# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

import sphinx_bootstrap_theme

# -- Project information -----------------------------------------------------

project = 'MantidProject'
copyright = '2021, Mantid'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = ''


# -- General configuration ---------------------------------------------------

extensions = []

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'bootstrap'
html_theme_path = sphinx_bootstrap_theme.get_html_theme_path()

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    'navbar_title': " ",  # Doesn't accept empty string
    'navbar_class': "navbar-right", 
    'navbar_links': [
        ("Downloads", "https://download.mantidproject.org/", 1),
        ("Guides", "Documentation"),
        ("Docs", "https://developer.mantidproject.org/", 1),
        ("News", "https://forum.mantidproject.org/c/news/8", 1),
        ("Forums", "https://forum.mantidproject.org/", 1),
        ("Contact Us", "Contact")
    ],
    'navbar_pagenav': False,
    'source_link_position': None,
}

html_static_path = ["_static"]

html_logo = "_static/images/Mantid_Logo_Transparent.png"

def setup(app):
    app.add_stylesheet("css/custom.css")